### ISSUE TITLE
Restrict the list of requestable users by repo

### ISSUE THREAD

**Issue by James-Firth** [James-Firth/git-slackin#25]
This would mean people outside of a project won't get requested to review PRs they know nothing about.

**Comment by James-Firth** [comment]
Mergers/Managers/Admins should also be restricted to particular repos this will help with the Multi-Team Milestone

**Comment by James-Firth** [comment]
I suppose really each user should have a list of repos they care about and a perhaps a `requestable`, `merger`, and `notifications` flag for each, in addition to the global one.

So for instance when checking if I should send a user a message it should look something like

```js
if (repo.notifications || user.global.notifications ) send a message
```

**Comment by KyleBrownCS** [comment]
I'll grab this
